version: '3.5'
services:
    webapp:
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
         - ./:/app
         - ./node_modules:/app/node_modules
    nginx:
      image: nginx:stable-alpine
      ports:
          - '8080:80'
      volumes:
          - ./:/app
          - ./conf/nginx.conf:/etc/nginx/nginx.conf
